scale_factor: 4
device: 'cuda:0'
batch_size: 1
lr : 0.0002
gamma: 0.5
start_epoch: 0
n_epochs: 80
n_steps: 30
data_dir: '/media/hamed/Local Disk/Phd_datasets/data/Carla_patches/patches'
test_data_dir: '/media/hamed/Local Disk/Phd_datasets/data/Carla'
load: False
checkpoints_dir: './checkpoints'
exp_name: 'test'
input_channel: 3
alpha: 0.0
model: 'NAFSSR'
w_size: 15
input_resolution: [30, 90]
val_split_ratio: 0.5
max_data_size : -1
